//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 3.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEditor;
using EasyExcel;

namespace EasyExcelGenerated
{
	[CustomEditor(typeof(PointEvent_Generated))]
	public class PointEventInspector_Generated : EEAssetInspector
	{
	}
}
