//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 3.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class Dialogue : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private string _ID;
		public string ID { get { return _ID; } }

		[SerializeField]
		private string _nameID;
		public string nameID { get { return _nameID; } }

		[SerializeField]
		private string _contentID;
		public string contentID { get { return _contentID; } }

		[SerializeField]
		private string _bgName;
		public string bgName { get { return _bgName; } }

		[SerializeField]
		private string _portraitName;
		public string portraitName { get { return _portraitName; } }

		[SerializeField]
		private string _portraitAnimationID;
		public string portraitAnimationID { get { return _portraitAnimationID; } }


		public Dialogue()
		{
		}

#if UNITY_EDITOR
		public Dialogue(List<List<string>> sheet, int row, int column)
		{
			_ID = sheet[row][column++] ?? "";
			_nameID = sheet[row][column++] ?? "";
			_contentID = sheet[row][column++] ?? "";
			_bgName = sheet[row][column++] ?? "";
			_portraitName = sheet[row][column++] ?? "";
			_portraitAnimationID = sheet[row][column++] ?? "";
		}
#endif
	}

	public class Dialogue_Generated : EERowDataCollection
	{
		[SerializeField]
		private List<Dialogue> elements = new List<Dialogue>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as Dialogue);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}
	}
}
