//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 3.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class GirlLevel : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private string _name;
		public string name { get { return _name; } }

		[SerializeField]
		private string[] _eventIDs;
		public string[] eventIDs { get { return _eventIDs; } }

		[SerializeField]
		private string _iconPath;
		public string iconPath { get { return _iconPath; } }


		public GirlLevel()
		{
		}

#if UNITY_EDITOR
		public GirlLevel(List<List<string>> sheet, int row, int column)
		{
			int.TryParse(sheet[row][column++], out _ID);
			_name = sheet[row][column++] ?? "";
			string[] _eventIDsArray = sheet[row][column++].Split(',');
			int _eventIDsCount = _eventIDsArray.Length;
			_eventIDs = new string[_eventIDsCount];
			for(int i = 0; i < _eventIDsCount; i++)
				_eventIDs[i] = _eventIDsArray[i];
			_iconPath = sheet[row][column++] ?? "";
		}
#endif
	}

	public class GirlLevel_Generated : EERowDataCollection
	{
		[SerializeField]
		private List<GirlLevel> elements = new List<GirlLevel>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as GirlLevel);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}
	}
}
