//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 3.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class Girl : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private string _name;
		public string name { get { return _name; } }

		[SerializeField]
		private string _height;
		public string height { get { return _height; } }

		[SerializeField]
		private string _measurement;
		public string measurement { get { return _measurement; } }

		[SerializeField]
		private string _birthday;
		public string birthday { get { return _birthday; } }

		[SerializeField]
		private string _hobby;
		public string hobby { get { return _hobby; } }


		public Girl()
		{
		}

#if UNITY_EDITOR
		public Girl(List<List<string>> sheet, int row, int column)
		{
			int.TryParse(sheet[row][column++], out _ID);
			_name = sheet[row][column++] ?? "";
			_height = sheet[row][column++] ?? "";
			_measurement = sheet[row][column++] ?? "";
			_birthday = sheet[row][column++] ?? "";
			_hobby = sheet[row][column++] ?? "";
		}
#endif
	}

	public class Girl_Generated : EERowDataCollection
	{
		[SerializeField]
		private List<Girl> elements = new List<Girl>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as Girl);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}
	}
}
