//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 3.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace EasyExcelGenerated
{
	[Serializable]
	public class PointEvent : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private string _ID;
		public string ID { get { return _ID; } }

		[SerializeField]
		private int _progress;
		public int progress { get { return _progress; } }

		[SerializeField]
		private string _dialogueID;
		public string dialogueID { get { return _dialogueID; } }

		[SerializeField]
		private string _cgID;
		public string cgID { get { return _cgID; } }


		public PointEvent()
		{
		}

#if UNITY_EDITOR
		public PointEvent(List<List<string>> sheet, int row, int column)
		{
			_ID = sheet[row][column++] ?? "";
			int.TryParse(sheet[row][column++], out _progress);
			_dialogueID = sheet[row][column++] ?? "";
			_cgID = sheet[row][column++] ?? "";
		}
#endif
	}

	public class PointEvent_Generated : EERowDataCollection
	{
		[SerializeField]
		private List<PointEvent> elements = new List<PointEvent>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as PointEvent);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}
	}
}
